import { useState, useEffect, useRef, useCallback, useMemo } from "react";

const C={red:"#E63225",rDk:"#C9271C",rBg:"#FFF0EF",dk:"#111",g9:"#1a1a1a",g7:"#444",g5:"#777",g4:"#999",g3:"#bbb",g2:"#ddd",g1:"#EFEFEF",g0:"#F7F7F7",wh:"#fff",bg:"#FAFAFA",gn:"#00B67A",gnB:"#EDFFF7",yl:"#FFB800",or:"#FF6B00",bl:"#2563EB",blB:"#EFF6FF"};
const R={s:8,m:12,l:16,x:20,f:999};const F="'Pretendard Variable','Pretendard',-apple-system,sans-serif";const MO="'JetBrains Mono',monospace";
function useCnt(t,d=1200){const[v,sv]=useState(0);useEffect(()=>{let s=null;const f=ts=>{if(!s)s=ts;const p=Math.min((ts-s)/d,1);sv(Math.floor((1-Math.pow(1-p,3))*t));if(p<1)requestAnimationFrame(f)};requestAnimationFrame(f)},[t,d]);return v}
function useCD(end){const[l,sl]=useState({h:0,m:0,s:0});useEffect(()=>{const t=()=>{const d=Math.max(0,end-Date.now());sl({h:Math.floor(d/36e5),m:Math.floor((d%36e5)/6e4),s:Math.floor((d%6e4)/1e3)})};t();const id=setInterval(t,1e3);return()=>clearInterval(id)},[end]);return l}
const pd=n=>String(n).padStart(2,"0"),fm=n=>n.toLocaleString("ko-KR");

const VIDEOS=["https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4","https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4","https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4","https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4","https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4","https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"];
const INF=[{id:"i1",name:"뷰티하는민지",short:"민지",fol:"12.4만",color:"#E86F8A",rate:98},{id:"i2",name:"건강한식탁",short:"효리",fol:"8.7만",color:"#7BAE5E",rate:96},{id:"i3",name:"리빙에디터소영",short:"채링",fol:"15.2만",color:"#6A7FDB",rate:99},{id:"i4",name:"나리스타일",short:"나리",fol:"55.8만",color:"#F59E0B",rate:97},{id:"i5",name:"머슬박사",short:"머슬",fol:"33.1만",color:"#E07A5F",rate:95},{id:"i6",name:"건강언니",short:"건강",fol:"22.4만",color:"#10B981",rate:94},{id:"i7",name:"하루뷰티",short:"하루",fol:"44.1만",color:"#9B72CF",rate:96}];
const P=[
  {id:1,name:"비건 클렌징 오일 200ml",desc:"식물성 오일 베이스, EWG 그린등급.",emoji:"🧴",gd:["#A8E6CF","#88D8B0"],price:18900,orig:32000,disc:41,cur:187,goal:200,hrs:2,inf:INF[0],cat:"뷰티",rv:324,rt:4.8,sold:1847,video:VIDEOS[0]},
  {id:2,name:"유기농 그래놀라 4종 세트",desc:"국내산 유기농 귀리+견과류.",emoji:"🥣",gd:["#FFD89B","#F0C27F"],price:24500,orig:38000,disc:36,cur:312,goal:500,hrs:18,inf:INF[1],cat:"식품",rv:589,rt:4.9,sold:3210,video:VIDEOS[1]},
  {id:3,name:"무선 미니 가습기 퓨어화이트",desc:"USB-C 충전, 초미세 미스트.",emoji:"💨",gd:["#A1C4FD","#C2E9FB"],price:29800,orig:49900,disc:40,cur:89,goal:150,hrs:48,inf:INF[2],cat:"리빙",rv:178,rt:4.6,sold:921,video:VIDEOS[2]},
  {id:4,name:"아기 보습 로션 300ml",desc:"EWG 그린등급, 24시간 보습.",emoji:"👶",gd:["#FCCB90","#EFA8B0"],price:15900,orig:26000,disc:39,cur:421,goal:500,hrs:6,inf:INF[3],cat:"육아",rv:1203,rt:4.9,sold:5847,video:VIDEOS[3]},
  {id:5,name:"프리미엄 단백질바 12개입",desc:"1개당 단백질 20g, 설탕 무첨가.",emoji:"💪",gd:["#D4A574","#C49A6C"],price:19900,orig:32000,disc:38,cur:156,goal:300,hrs:24,inf:INF[4],cat:"식품",rv:445,rt:4.7,sold:2340,video:VIDEOS[4]},
  {id:6,name:"실크 수면안대+파우치 세트",desc:"100% 멀베리 실크.",emoji:"😴",gd:["#C9B1FF","#B8A0E8"],price:12900,orig:22000,disc:41,cur:267,goal:300,hrs:10,inf:INF[5],cat:"리빙",rv:891,rt:4.8,sold:4120,video:VIDEOS[5]},
];
const CAPTS=["클렌징 오일 리뷰 🧴✨","그래놀라 언박싱 🥣","가습기 실화? 💨","아기 로션 끝판왕 👶","단백질바 리뷰 💪","실크 안대 후기 😴"];
const CATS=["전체","뷰티","식품","리빙","육아"];
const RV=[{name:"지*은",r:5,text:"진짜 순해요! 자극 없었어요.",date:"2일 전",help:42},{name:"혜*리",r:5,text:"세정력 미쳤어요 재구매 확정!",date:"3일 전",help:38},{name:"수*아",r:5,text:"아이메이크업도 깔끔!",date:"5일 전",help:27},{name:"민*정",r:4,text:"세정력 확실. 만족!",date:"1주 전",help:15}];
const OD=[
  {id:"G240411001",product:P[0],qty:2,total:37800,status:"공구진행중",date:"2026.04.11",track:null,curP:187,goalP:200,hrsLeft:2,pay:"카카오페이",addr:"서울 강남구 테헤란로 123"},
  {id:"G240409002",product:P[3],qty:1,total:15900,status:"배송중",date:"2026.04.09",track:"CJ대한통운 629184729381",curP:null,goalP:null,hrsLeft:null,pay:"토스페이",addr:"서울 마포구 양화로 45"},
  {id:"G240406003",product:P[1],qty:1,total:24500,status:"배송중",date:"2026.04.06",track:"한진택배 564812937462",curP:null,goalP:null,hrsLeft:null,pay:"카카오페이",addr:"서울 강남구 테헤란로 123"},
  {id:"G240403004",product:P[5],qty:3,total:38700,status:"배송완료",date:"2026.04.03",track:"CJ대한통운 629184722145",curP:null,goalP:null,hrsLeft:null,pay:"신용카드",addr:"서울 강남구 테헤란로 123"},
  {id:"G240328005",product:P[4],qty:2,total:39800,status:"배송완료",date:"2026.03.28",track:"로젠택배 193847562738",curP:null,goalP:null,hrsLeft:null,pay:"카카오페이",addr:"서울 마포구 양화로 45"},
];
const NOTIFS=[{id:1,icon:"🔥",title:"마감임박! 비건 클렌징 오일",body:"2시간 후 마감",time:"10분 전",read:false,pid:1},{id:2,icon:"🎉",title:"새 공구 오픈!",body:"건강한식탁님의 새 공구",time:"1시간 전",read:false,pid:null},{id:3,icon:"🚚",title:"배송 시작",body:"아기 보습 로션 - CJ대한통운",time:"3시간 전",read:true,pid:null},{id:4,icon:"✅",title:"공구 달성!",body:"실크 수면안대 세트",time:"어제",read:true,pid:6},{id:5,icon:"💰",title:"포인트 적립",body:"159P 적립 완료",time:"2일 전",read:true,pid:null},{id:6,icon:"🎫",title:"새 쿠폰 도착",body:"뷰티 3,000원 할인",time:"3일 전",read:true,pid:null}];
const COUPONS=[{id:1,name:"첫 구매 할인",amount:2000,min:15000,exp:"2026.04.30",used:false},{id:2,name:"뷰티 카테고리",amount:3000,min:20000,exp:"2026.05.15",used:false},{id:3,name:"주말 특별",amount:1500,min:10000,exp:"2026.04.20",used:false},{id:4,name:"리뷰 감사",amount:1000,min:5000,exp:"2026.03.30",used:true}];
const PLOG=[{id:1,desc:"실크 수면안대 구매확정",amount:387,type:"+",date:"2026.04.05"},{id:2,desc:"단백질바 구매확정",amount:398,type:"+",date:"2026.03.30"},{id:3,desc:"후기 작성 보상",amount:500,type:"+",date:"2026.03.29"},{id:4,desc:"쿠폰 교환",amount:-1000,type:"-",date:"2026.03.25"},{id:5,desc:"클렌징 오일 구매확정",amount:189,type:"+",date:"2026.03.20"},{id:6,desc:"회원가입 축하",amount:1000,type:"+",date:"2026.03.15"}];
const MY_RV=[{id:1,product:P[5],rating:5,text:"실크 소재 진짜 부드럽고 빛 차단 완벽!",date:"2026.04.05"},{id:2,product:P[4],rating:4,text:"단백질 함량 좋고 초코맛 최고.",date:"2026.03.30"}];
const EVENTS=[{id:1,emoji:"🎁",title:"친구 초대하면 5,000P!",desc:"초대 링크로 친구가 가입하면 서로 5,000P 적립",period:"~2026.05.31",tag:"진행중"},{id:2,emoji:"⭐",title:"후기 쓰면 500P",desc:"구매 확정 후 50자 이상 후기 작성 시",period:"상시 진행",tag:"상시"},{id:3,emoji:"📱",title:"앱 설치 이벤트",desc:"앱 최초 설치 시 3,000원 쿠폰 지급",period:"~2026.04.30",tag:"마감임박"}];
const FAQ=[{q:"주문 취소는 어떻게 하나요?",a:"공구 마감 전이면 주문내역에서 취소 가능합니다. 마감 후에는 배송 시작 전까지만 취소할 수 있어요."},{q:"배송은 얼마나 걸리나요?",a:"공구 마감 후 3영업일 이내 발송되며, 발송 후 1~2일 내 수령 가능합니다."},{q:"교환/반품 하고 싶어요",a:"수령 후 7일 이내 교환·반품 신청 가능합니다. 단순변심은 배송비 소비자 부담이에요."},{q:"포인트는 어떻게 사용하나요?",a:"결제 시 1P = 1원으로 사용 가능합니다. 최소 1,000P 이상부터 사용할 수 있어요."},{q:"쿠폰은 중복 사용 가능한가요?",a:"쿠폰은 주문당 1장만 적용 가능합니다."}];
const SM={공구진행중:{c:C.or,bg:"#FFF4EC"},배송준비중:{c:C.bl,bg:C.blB},배송중:{c:C.gn,bg:C.gnB},배송완료:{c:C.g4,bg:C.g0}};

/* ═══ ATOMS ═══ */
const Timer=({end,size="md"})=>{const l=useCD(end);const s=size==="sm";return(<div style={{display:"flex",gap:s?2:4,alignItems:"center"}}>{[l.h,l.m,l.s].map((v,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:s?2:4}}><span style={{background:C.g9,color:C.wh,padding:s?"2px 5px":"4px 8px",borderRadius:s?4:6,fontFamily:MO,fontSize:s?12:16,fontWeight:700,minWidth:s?24:32,textAlign:"center"}}>{pd(v)}</span>{i<2&&<span style={{color:C.g3,fontWeight:700,fontSize:s?10:13}}>:</span>}</div>))}</div>)};
const Bar=({cur,goal,h=5,label=true})=>{const pct=Math.min(cur/goal*100,100);const hot=pct>=85;return(<div style={{width:"100%"}}>{label&&<div style={{display:"flex",justifyContent:"space-between",marginBottom:4,fontSize:12,fontFamily:F}}><span style={{color:C.g7}}><b style={{color:hot?C.red:C.dk,fontWeight:800}}>{fm(cur)}명</b> 참여</span><span style={{color:C.g4}}>목표 {fm(goal)}명</span></div>}<div style={{width:"100%",height:h,background:C.g1,borderRadius:R.f,overflow:"hidden"}}><div style={{width:`${pct}%`,height:"100%",background:hot?`linear-gradient(90deg,${C.red},${C.rDk})`:`linear-gradient(90deg,${C.red}bb,${C.red}88)`,borderRadius:R.f,transition:"width .8s cubic-bezier(.22,1,.36,1)"}}/></div></div>)};
const Stars=({r,size=12})=>(<span style={{display:"inline-flex",gap:1}}>{[1,2,3,4,5].map(i=>(<span key={i} style={{fontSize:size,color:i<=Math.round(r)?C.yl:C.g2}}>★</span>))}</span>);
const Bdg=({children,bg=C.dk,color=C.wh,pulse})=>(<span style={{display:"inline-flex",alignItems:"center",gap:3,background:bg,color,fontSize:11,fontWeight:700,padding:"3px 9px",borderRadius:R.f,fontFamily:F,animation:pulse?"bp 2s infinite":"none"}}>{children}</span>);
const PImg=({p,style:s={},children})=>(<div style={{position:"relative",background:`linear-gradient(145deg,${p.gd[0]}55,${p.gd[1]}88)`,overflow:"hidden",...s}}><div style={{position:"absolute",top:"-20%",right:"-15%",width:"50%",paddingTop:"50%",borderRadius:"50%",background:`${p.gd[0]}44`}}/><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:68}}>{p.emoji}</div>{children}</div>);
const Hdr=({title,left,right,onLeft})=>(<div style={{position:"sticky",top:0,zIndex:20,height:48,background:"rgba(250,250,250,.97)",borderBottom:`1px solid ${C.g1}`,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 14px"}}>{left?<span onClick={onLeft} style={{width:36,height:36,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",fontSize:20}}>←</span>:<div style={{width:36}}/>}<span style={{fontSize:14,fontWeight:700,fontFamily:F}}>{title}</span>{right||<div style={{width:36}}/>}</div>);
const Thumb=({p,size=64})=>(<div style={{width:size,height:size,borderRadius:R.m,background:`linear-gradient(135deg,${p.gd[0]}55,${p.gd[1]}88)`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:size*.42,flexShrink:0}}>{p.emoji}</div>);
/* Pressable wrapper for touch feedback */
function Tap({children,onClick,style={}}){const[pressed,setPressed]=useState(false);return(<div onClick={onClick} onPointerDown={()=>setPressed(true)} onPointerUp={()=>setPressed(false)} onPointerLeave={()=>setPressed(false)} style={{...style,transform:pressed?"scale(0.97)":"scale(1)",transition:"transform .12s ease",cursor:"pointer"}}>{children}</div>)}

function Card({item,onClick,i=0}){const u=item.hrs<=3;return(<Tap onClick={onClick} style={{background:C.wh,borderRadius:R.l,overflow:"hidden",border:`1px solid ${C.g1}`,animation:`fu .4s ease ${i*.05}s both`}}><PImg p={item} style={{paddingTop:"100%"}}><div style={{position:"absolute",top:8,left:8,display:"flex",gap:4}}>{u&&<Bdg bg={C.red} pulse>마감임박</Bdg>}<Bdg bg="rgba(0,0,0,.6)">{item.disc}%</Bdg></div><div style={{position:"absolute",bottom:8,left:8,display:"flex",alignItems:"center",gap:4,background:"rgba(0,0,0,.55)",borderRadius:R.f,padding:"2px 8px 2px 5px"}}><span style={{width:5,height:5,borderRadius:"50%",background:"#4ADE80"}}/><span style={{color:C.wh,fontSize:10,fontWeight:600,fontFamily:MO}}>{fm(item.cur)}</span></div></PImg><div style={{padding:"10px 12px 12px"}}><div style={{display:"flex",alignItems:"center",gap:3,marginBottom:4}}><span style={{width:12,height:12,borderRadius:"50%",background:item.inf.color,display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:7,color:C.wh,fontWeight:800}}>✓</span><span style={{fontSize:11,color:C.g4,fontFamily:F}}>{item.inf.name}</span></div><h3 style={{margin:"0 0 6px",fontSize:14,fontWeight:700,color:C.dk,lineHeight:1.4,fontFamily:F,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{item.name}</h3><div style={{display:"flex",alignItems:"baseline",gap:4,marginBottom:8}}><span style={{fontSize:16,fontWeight:900,color:C.red,fontFamily:F}}>{fm(item.price)}<span style={{fontSize:11}}>원</span></span><span style={{fontSize:11,color:C.g3,textDecoration:"line-through"}}>{fm(item.orig)}원</span></div><Bar cur={item.cur} goal={item.goal} label={false} h={3}/></div></Tap>)}
function SellerBubble({inf,onClick}){return(<Tap onClick={onClick} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:5,minWidth:72}}><div style={{width:62,height:62,borderRadius:"50%",background:`linear-gradient(135deg,${C.red},${C.rDk})`,padding:3}}><div style={{width:"100%",height:"100%",borderRadius:"50%",background:`linear-gradient(135deg,${inf.color},${inf.color}cc)`,display:"flex",alignItems:"center",justifyContent:"center",color:C.wh,fontSize:16,fontWeight:900,fontFamily:F,border:`2.5px solid ${C.wh}`}}>{inf.short}</div></div><span style={{fontSize:10,color:C.g4,fontFamily:MO,fontWeight:600}}>{inf.fol}</span><span style={{fontSize:11,fontWeight:600,color:C.g7,fontFamily:F,maxWidth:72,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginTop:-2}}>{inf.name}</span></Tap>)}
/* Menu Row */
function MenuRow({icon,label,onClick}){return(<Tap onClick={onClick} style={{padding:"14px 16px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:18}}>{icon}</span><span style={{fontSize:14,fontFamily:F}}>{label}</span></div><span style={{color:C.g3}}>›</span></Tap>)}

/* ═══ HOME ═══ */
function Home({go,detail}){const[cat,setCat]=useState("전체");const[sort,setSort]=useState("인기순");const live=useCnt(1247);const list=useMemo(()=>{let l=cat==="전체"?P:P.filter(p=>p.cat===cat);if(sort==="마감임박")l=[...l].sort((a,b)=>a.hrs-b.hrs);if(sort==="할인율순")l=[...l].sort((a,b)=>b.disc-a.disc);return l},[cat,sort]);const urgent=P.filter(p=>p.hrs<=6);
  return(<div style={{paddingBottom:70}}>
    <div style={{position:"sticky",top:0,zIndex:20,background:"rgba(250,250,250,.97)",padding:"0 20px",height:52,display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:`1px solid ${C.g1}`}}><div><span style={{fontSize:22,fontWeight:900,color:C.dk,fontFamily:F,letterSpacing:-.5}}>GUGU</span><span style={{fontSize:22,fontWeight:900,color:C.red}}>.</span></div><div style={{display:"flex",gap:8,alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:4,padding:"4px 10px",background:C.rBg,borderRadius:R.f}}><span style={{width:5,height:5,borderRadius:"50%",background:C.red,animation:"bp 2s infinite"}}/><span style={{fontSize:11,fontWeight:700,color:C.red,fontFamily:MO}}>{fm(live)}</span></div><Tap onClick={()=>go("notif")} style={{width:34,height:34,borderRadius:"50%",background:C.g0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,border:`1px solid ${C.g1}`,position:"relative"}}>🔔<span style={{position:"absolute",top:4,right:4,width:6,height:6,borderRadius:"50%",background:C.red,border:`1.5px solid ${C.wh}`}}/></Tap><Tap onClick={()=>go("search")} style={{width:34,height:34,borderRadius:"50%",background:C.g0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,border:`1px solid ${C.g1}`}}>🔍</Tap></div></div>
    <div style={{padding:"14px 20px 0"}}><Tap onClick={()=>detail(P[0])} style={{background:`linear-gradient(135deg,${C.dk},#252525)`,borderRadius:R.x,padding:"20px 18px 18px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:-40,right:-30,width:140,height:140,borderRadius:"50%",background:`${C.red}18`}}/><div style={{position:"relative",zIndex:1}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:8}}><Bdg bg={C.red} pulse>HOT</Bdg><span style={{fontSize:11,color:C.g4,fontFamily:MO}}>오늘의 추천</span></div><h2 style={{color:C.wh,fontSize:19,fontWeight:800,margin:"0 0 2px",fontFamily:F}}>비건 클렌징 오일 41% 할인</h2><p style={{color:C.g5,fontSize:12,margin:"0 0 16px",fontFamily:F}}>뷰티하는민지 × GUGU 단독</p><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><Timer end={Date.now()+2*36e5}/><div style={{background:C.red,color:C.wh,fontSize:13,fontWeight:700,padding:"10px 20px",borderRadius:R.f,fontFamily:F}}>참여하기</div></div></div></Tap></div>
    {urgent.length>0&&<div style={{padding:"18px 0 0"}}><div style={{padding:"0 20px",display:"flex",alignItems:"center",gap:6,marginBottom:10}}><span style={{fontSize:16}}>🔥</span><h3 style={{margin:0,fontSize:15,fontWeight:800,color:C.red,fontFamily:F}}>마감임박</h3></div><div style={{display:"flex",gap:10,overflowX:"auto",padding:"0 20px",scrollbarWidth:"none"}}>{urgent.map(p=>(<Tap key={p.id} onClick={()=>detail(p)} style={{minWidth:240,background:C.wh,borderRadius:R.l,border:`1px solid ${C.red}22`,flexShrink:0,padding:12}}><div style={{display:"flex",gap:12}}><Thumb p={p}/><div><p style={{margin:0,fontSize:13,fontWeight:700,fontFamily:F}}>{p.name}</p><div style={{display:"flex",alignItems:"baseline",gap:4,margin:"4px 0 6px"}}><span style={{fontSize:14,fontWeight:900,color:C.red,fontFamily:F}}>{p.disc}%</span><span style={{fontSize:13,fontWeight:700,fontFamily:F}}>{fm(p.price)}원</span></div><Timer end={Date.now()+p.hrs*36e5} size="sm"/></div></div></Tap>))}</div></div>}
    <div style={{padding:"18px 0 0"}}><div style={{padding:"0 20px",marginBottom:12}}><h3 style={{margin:0,fontSize:15,fontWeight:800,fontFamily:F}}>인기 셀러</h3></div><div style={{display:"flex",gap:12,overflowX:"auto",padding:"0 20px 6px",scrollbarWidth:"none"}}>{INF.map(inf=>(<SellerBubble key={inf.id} inf={inf} onClick={()=>go("influencer",{inf})}/>))}</div></div>
    <div style={{position:"sticky",top:52,zIndex:15,background:C.bg,padding:"14px 20px 0"}}><div style={{display:"flex",gap:6,overflowX:"auto",scrollbarWidth:"none",paddingBottom:10}}>{CATS.map(c=>(<button key={c} onClick={()=>setCat(c)} style={{padding:"7px 16px",borderRadius:R.f,border:"none",background:cat===c?C.dk:C.wh,color:cat===c?C.wh:C.g5,fontSize:13,fontWeight:cat===c?700:500,cursor:"pointer",whiteSpace:"nowrap",fontFamily:F}}>{c}</button>))}</div><div style={{display:"flex",justifyContent:"space-between",paddingBottom:8,borderBottom:`1px solid ${C.g1}`}}><span style={{fontSize:14,fontWeight:800,fontFamily:F}}>진행중 <span style={{color:C.red,fontFamily:MO}}>{list.length}</span></span><div style={{display:"flex",gap:8}}>{["인기순","마감임박","할인율순"].map(s=>(<span key={s} onClick={()=>setSort(s)} style={{fontSize:12,color:sort===s?C.dk:C.g4,fontWeight:sort===s?700:400,cursor:"pointer",fontFamily:F}}>{s}</span>))}</div></div></div>
    <div style={{padding:"10px 20px 0",display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{list.map((p,i)=>(<Card key={p.id} item={p} i={i} onClick={()=>detail(p)}/>))}</div>
  </div>);
}

/* ═══ SEARCH ═══ */
function SearchPage({go,detail}){const[q,setQ]=useState("");const res=q.length>0?P.filter(p=>p.name.includes(q)||p.inf.name.includes(q)||p.cat.includes(q)):[];
  return(<div style={{paddingBottom:70}}><div style={{position:"sticky",top:0,zIndex:20,background:"rgba(250,250,250,.97)",padding:"8px 16px",display:"flex",alignItems:"center",gap:10,borderBottom:`1px solid ${C.g1}`}}><span onClick={()=>go("home")} style={{fontSize:20,cursor:"pointer"}}>←</span><div style={{flex:1,background:C.wh,borderRadius:R.m,padding:"10px 14px",display:"flex",alignItems:"center",gap:8,border:`1px solid ${q?C.red:C.g1}`}}><span style={{fontSize:14,opacity:.35}}>🔍</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="검색어를 입력해주세요" autoFocus style={{border:"none",outline:"none",background:"transparent",fontSize:16,fontFamily:F,width:"100%",padding:0}}/>{q&&<span onClick={()=>setQ("")} style={{fontSize:16,color:C.g3,cursor:"pointer"}}>✕</span>}</div></div>
    {q.length===0?<div style={{padding:20}}><h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:700,fontFamily:F}}>인기 검색어</h3><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{["비건","클렌징","이유식","단백질","가습기","선크림","그래놀라","실크"].map((w,i)=>(<span key={w} onClick={()=>setQ(w)} style={{padding:"8px 16px",background:C.wh,borderRadius:R.f,fontSize:13,color:C.g7,fontFamily:F,cursor:"pointer",border:`1px solid ${C.g1}`,display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:12,color:C.red,fontWeight:700,fontFamily:MO}}>{i+1}</span>{w}</span>))}</div><h3 style={{margin:"24px 0 12px",fontSize:15,fontWeight:700,fontFamily:F}}>카테고리</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{[{e:"💄",l:"뷰티",c:"#FDE8E8"},{e:"🍽️",l:"식품",c:"#FEF3C7"},{e:"🏠",l:"리빙",c:"#DBEAFE"},{e:"👶",l:"육아",c:"#FCE7F3"}].map(c=>(<Tap key={c.l} onClick={()=>setQ(c.l)} style={{padding:16,background:c.c,borderRadius:R.l,display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:28}}>{c.e}</span><span style={{fontSize:14,fontWeight:700,fontFamily:F}}>{c.l}</span></Tap>))}</div></div>:
    <div style={{padding:"10px 20px"}}><p style={{fontSize:13,color:C.g4,fontFamily:F,marginBottom:12}}>검색결과 <b style={{color:C.dk}}>{res.length}</b>건</p>{res.length===0?<div style={{textAlign:"center",padding:"40px 0"}}><div style={{fontSize:48,marginBottom:12}}>🔍</div><p style={{fontSize:14,color:C.g4,fontFamily:F}}>"{q}" 결과 없음</p></div>:<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{res.map((p,i)=>(<Card key={p.id} item={p} i={i} onClick={()=>detail(p)}/>))}</div>}</div>}
  </div>);
}

/* ═══ DETAIL ═══ */
function Detail({product:p,goBack,go}){const[joined,setJoined]=useState(false);const[tab,setTab]=useState("info");const[qty,setQty]=useState(1);const[sheet,setSheet]=useState(false);const[wish,setWish]=useState(false);const cur=useCnt(joined?p.cur+1:p.cur,600);const u=p.hrs<=6;const related=P.filter(x=>x.id!==p.id&&(x.inf.id===p.inf.id||x.cat===p.cat)).slice(0,4);
  return(<div style={{paddingBottom:76,background:C.bg}}>
    <Hdr title="공구 상세" left onLeft={goBack} right={<span onClick={()=>setWish(!wish)} style={{fontSize:18,cursor:"pointer"}}>{wish?"❤️":"🤍"}</span>}/>
    <div style={{position:"relative",width:"100%",aspectRatio:"9/11",background:"#000"}}><video src={p.video} autoPlay muted loop playsInline style={{width:"100%",height:"100%",objectFit:"cover"}}/><div style={{position:"absolute",bottom:0,left:0,right:0,height:"35%",background:"linear-gradient(transparent,rgba(0,0,0,.45))",pointerEvents:"none"}}/><div style={{position:"absolute",top:12,left:12,display:"flex",gap:5}}>{u&&<Bdg bg={C.red} pulse>마감임박</Bdg>}<Bdg bg="rgba(0,0,0,.6)">{p.disc}% OFF</Bdg></div><div style={{position:"absolute",bottom:12,left:12,right:12,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:4,background:"rgba(0,0,0,.6)",borderRadius:R.f,padding:"4px 10px 4px 6px"}}><span style={{width:5,height:5,borderRadius:"50%",background:"#4ADE80"}}/><span style={{color:C.wh,fontSize:11,fontWeight:600,fontFamily:MO}}>{fm(cur)}명</span></div><Timer end={Date.now()+p.hrs*36e5} size="sm"/></div></div>
    <Tap onClick={()=>go("influencer",{inf:p.inf})} style={{padding:"12px 20px",display:"flex",alignItems:"center",gap:10,background:C.wh,borderBottom:`1px solid ${C.g1}`}}><div style={{width:42,height:42,borderRadius:"50%",background:`linear-gradient(135deg,${C.red},${C.rDk})`,padding:2}}><div style={{width:"100%",height:"100%",borderRadius:"50%",background:`linear-gradient(135deg,${p.inf.color},${p.inf.color}cc)`,display:"flex",alignItems:"center",justifyContent:"center",color:C.wh,fontSize:14,fontWeight:800,border:`2px solid ${C.wh}`}}>{p.inf.short}</div></div><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:14,fontWeight:700,fontFamily:F}}>{p.inf.name}</span><span style={{background:C.red,color:C.wh,fontSize:8,fontWeight:800,padding:"2px 6px",borderRadius:3}}>인증</span></div><p style={{margin:"1px 0 0",fontSize:11,color:C.g4}}>팔로워 {p.inf.fol}</p></div><span style={{color:C.g3}}>›</span></Tap>
    <div style={{padding:"16px 20px",background:C.wh}}><h1 style={{margin:0,fontSize:18,fontWeight:800,lineHeight:1.4,fontFamily:F}}>{p.name}</h1><div style={{display:"flex",alignItems:"center",gap:6,margin:"8px 0 2px"}}><Stars r={p.rt} size={13}/><span style={{fontSize:13,fontWeight:700}}>{p.rt}</span><span style={{fontSize:12,color:C.g4}}>({fm(p.rv)})</span><span style={{color:C.g2}}>·</span><span style={{fontSize:12,color:C.g4}}>{fm(p.sold)}개 판매</span></div><div style={{display:"flex",alignItems:"baseline",gap:6,margin:"10px 0 0"}}><span style={{fontSize:26,fontWeight:900,color:C.red,fontFamily:F}}>{p.disc}%</span><span style={{fontSize:24,fontWeight:800,fontFamily:F}}>{fm(p.price)}<span style={{fontSize:14}}>원</span></span></div><span style={{fontSize:13,color:C.g3,textDecoration:"line-through"}}>{fm(p.orig)}원</span></div>
    <div style={{margin:"6px 0",padding:"16px 20px",background:C.wh}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:12}}><span style={{width:7,height:7,borderRadius:"50%",background:C.red,animation:"bp 2s infinite"}}/><span style={{fontSize:13,fontWeight:700,color:C.red,fontFamily:F}}>실시간 현황</span></div><Bar cur={cur} goal={p.goal}/></div>
    <div style={{display:"flex",background:C.wh,borderBottom:`1px solid ${C.g1}`,position:"sticky",top:48,zIndex:15}}>{[{id:"info",l:"상품정보"},{id:"review",l:`후기 ${fm(p.rv)}`},{id:"policy",l:"배송/교환"}].map(t=>(<div key={t.id} onClick={()=>setTab(t.id)} style={{flex:1,textAlign:"center",padding:"12px 0",cursor:"pointer",fontSize:13,fontWeight:tab===t.id?700:400,color:tab===t.id?C.dk:C.g4,borderBottom:tab===t.id?`2px solid ${C.dk}`:"2px solid transparent",fontFamily:F}}>{t.l}</div>))}</div>
    <div style={{background:C.wh,minHeight:180}}>
      {tab==="info"&&<div style={{padding:20}}><p style={{margin:"0 0 16px",fontSize:14,color:C.g5,lineHeight:1.75,fontFamily:F}}>{p.desc}</p><div style={{padding:14,background:C.g0,borderRadius:R.m,borderLeft:`3px solid ${p.inf.color}`}}><p style={{margin:0,fontSize:13,color:C.g7,fontStyle:"italic",lineHeight:1.6}}>"{p.name} 직접 써보고 열었어요! 💛"</p><p style={{margin:"6px 0 0",fontSize:12,color:C.g4}}>— {p.inf.name}</p></div></div>}
      {tab==="review"&&<div style={{padding:20}}>{RV.map((r,i)=>(<div key={i} style={{padding:14,background:C.g0,borderRadius:R.m,marginBottom:6}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><div style={{display:"flex",alignItems:"center",gap:6}}><Stars r={r.r} size={11}/><span style={{fontSize:12,fontWeight:600}}>{r.name}</span></div><span style={{fontSize:10,color:C.g3}}>{r.date}</span></div><p style={{margin:0,fontSize:13,color:C.g7,lineHeight:1.6}}>{r.text}</p></div>))}</div>}
      {tab==="policy"&&<div style={{padding:20}}>{[{t:"배송",items:["마감 후 3영업일 내 발송","CJ대한통운"]},{t:"교환/반품",items:["수령 후 7일 이내"]},{t:"환불",items:["마감 전 전액 환불"]}].map((s,i)=>(<div key={i} style={{marginBottom:i<2?14:0}}><h4 style={{margin:"0 0 6px",fontSize:14,fontWeight:700,fontFamily:F}}>{s.t}</h4>{s.items.map((x,j)=>(<div key={j} style={{fontSize:13,color:C.g5,lineHeight:1.6,marginBottom:2}}>· {x}</div>))}</div>))}</div>}
    </div>
    {related.length>0&&<div style={{padding:"16px 20px"}}><h3 style={{margin:"0 0 10px",fontSize:15,fontWeight:800,fontFamily:F}}>함께 보면 좋은 공구</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{related.map((r,i)=>(<Card key={r.id} item={r} i={i} onClick={()=>{goBack();setTimeout(()=>go("detail",{product:r}),50)}}/>))}</div></div>}
    <div style={{position:"fixed",bottom:0,left:0,right:0,maxWidth:480,margin:"0 auto",padding:"8px 20px",paddingBottom:"calc(8px + env(safe-area-inset-bottom,0px))",background:"rgba(255,255,255,.98)",borderTop:`1px solid ${C.g1}`,zIndex:20}}>
      {!sheet?<div style={{display:"flex",gap:8,alignItems:"center"}}><Tap onClick={()=>setWish(!wish)} style={{padding:"6px 10px"}}><span style={{fontSize:20}}>{wish?"❤️":"🤍"}</span></Tap><button onClick={()=>{if(joined)return;setSheet(true)}} style={{flex:1,padding:"14px 0",borderRadius:R.m,border:"none",background:joined?C.dk:`linear-gradient(135deg,${C.red},${C.rDk})`,color:C.wh,fontSize:15,fontWeight:800,cursor:"pointer",fontFamily:F,boxShadow:joined?"none":`0 4px 18px ${C.red}44`,transition:"all .2s"}}>{joined?"✓ 참여 완료":"공구 참여하기"}</button></div>:
      <div style={{animation:"su .2s ease"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><span style={{fontSize:14,fontWeight:700}}>수량 선택</span><span onClick={()=>setSheet(false)} style={{fontSize:18,cursor:"pointer",color:C.g4}}>✕</span></div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"10px 14px",background:C.g0,borderRadius:R.m,marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:14}}><Tap onClick={()=>setQty(Math.max(1,qty-1))} style={{width:30,height:30,borderRadius:R.f,border:`1px solid ${C.g2}`,display:"flex",alignItems:"center",justifyContent:"center",background:C.wh}}>−</Tap><span style={{fontSize:17,fontWeight:700,fontFamily:MO}}>{qty}</span><Tap onClick={()=>setQty(Math.min(10,qty+1))} style={{width:30,height:30,borderRadius:R.f,border:`1px solid ${C.g2}`,display:"flex",alignItems:"center",justifyContent:"center",background:C.wh}}>+</Tap></div><span style={{fontSize:17,fontWeight:800}}>{fm(p.price*qty)}원</span></div><button onClick={()=>go("checkout",{product:p,qty})} style={{width:"100%",padding:"14px 0",borderRadius:R.m,border:"none",background:`linear-gradient(135deg,${C.red},${C.rDk})`,color:C.wh,fontSize:15,fontWeight:800,cursor:"pointer",fontFamily:F}}>구매하기</button></div>}
    </div>
    {joined&&<div style={{position:"fixed",top:60,left:16,right:16,maxWidth:448,margin:"0 auto",padding:"12px 16px",background:C.dk,color:C.wh,borderRadius:R.m,display:"flex",alignItems:"center",gap:10,zIndex:50,animation:"sd .3s ease,fo .3s ease 2.5s forwards"}}><span style={{fontSize:20}}>🎉</span><p style={{margin:0,fontSize:13,fontWeight:700}}>공구 참여 완료!</p></div>}
  </div>);
}

/* ═══ CHECKOUT ═══ */
function Checkout({product:p,qty:initQ,goBack,go}){const[coupon,setCoupon]=useState(false);const[payMethod,setPayMethod]=useState("카카오페이");const q=initQ||1;const sub=p.price*q;const disc=coupon?2000:0;const total=sub-disc;
  return(<div style={{paddingBottom:90,background:C.g0}}>
    <Hdr title="결제하기" left onLeft={goBack}/>
    <div style={{margin:"6px 0",padding:16,background:C.wh}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><h3 style={{margin:0,fontSize:15,fontWeight:800,fontFamily:F}}>배송지</h3><span style={{fontSize:12,color:C.red,fontWeight:600,cursor:"pointer"}}>변경</span></div><p style={{margin:0,fontSize:14,fontWeight:700}}>홍길동 · 010-1234-5678</p><p style={{margin:"4px 0 0",fontSize:13,color:C.g5,lineHeight:1.5}}>서울특별시 강남구 테헤란로 123, 4층</p><input placeholder="배송 요청사항" style={{marginTop:10,width:"100%",padding:"10px 12px",borderRadius:R.s,border:`1px solid ${C.g1}`,fontSize:14,fontFamily:F,outline:"none",boxSizing:"border-box"}}/></div>
    <div style={{margin:"0 0 6px",padding:16,background:C.wh}}><h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:800}}>주문 상품</h3><div style={{display:"flex",gap:12}}><Thumb p={p}/><div><p style={{margin:0,fontSize:14,fontWeight:700}}>{p.name}</p><p style={{margin:"3px 0",fontSize:12,color:C.g4}}>수량 {q}개</p><p style={{margin:0,fontSize:15,fontWeight:800}}>{fm(sub)}원</p></div></div></div>
    <div style={{margin:"0 0 6px",padding:16,background:C.wh}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h3 style={{margin:0,fontSize:15,fontWeight:800}}>쿠폰</h3><Tap onClick={()=>setCoupon(!coupon)} style={{display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:13,color:coupon?C.red:C.g4,fontWeight:600}}>{coupon?"첫 구매 -2,000원":"사용 가능 1장"}</span><div style={{width:20,height:20,borderRadius:4,border:`2px solid ${coupon?C.red:C.g2}`,background:coupon?C.red:C.wh,display:"flex",alignItems:"center",justifyContent:"center"}}>{coupon&&<span style={{color:C.wh,fontSize:12,fontWeight:800}}>✓</span>}</div></Tap></div></div>
    <div style={{margin:"0 0 6px",padding:16,background:C.wh}}><h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:800}}>결제수단</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{[{l:"카카오페이",i:"💛"},{l:"토스페이",i:"💙"},{l:"신용카드",i:"💳"},{l:"무통장",i:"🏦"}].map(m=>(<Tap key={m.l} onClick={()=>setPayMethod(m.l)} style={{padding:12,borderRadius:R.s,border:`1.5px solid ${payMethod===m.l?C.dk:C.g1}`,background:payMethod===m.l?`${C.dk}08`:C.wh,display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:18}}>{m.i}</span><span style={{fontSize:13,fontWeight:payMethod===m.l?700:500}}>{m.l}</span></Tap>))}</div></div>
    <div style={{padding:16,background:C.wh}}><h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:800}}>결제 금액</h3>{[{l:"상품 금액",v:fm(sub)+"원"},{l:"배송비",v:"무료"},{l:"쿠폰 할인",v:disc>0?`-${fm(disc)}원`:"없음"}].map(r=>(<div key={r.l} style={{display:"flex",justifyContent:"space-between",marginBottom:6,fontSize:13}}><span style={{color:C.g5}}>{r.l}</span><span style={{color:r.l.includes("할인")&&disc>0?C.red:C.dk,fontWeight:500}}>{r.v}</span></div>))}<div style={{borderTop:`1px solid ${C.g1}`,paddingTop:10,marginTop:6,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:14,fontWeight:700}}>총 결제</span><span style={{fontSize:20,fontWeight:900,color:C.red}}>{fm(total)}원</span></div></div>
    <div style={{position:"fixed",bottom:0,left:0,right:0,maxWidth:480,margin:"0 auto",padding:"8px 20px",paddingBottom:"calc(8px + env(safe-area-inset-bottom,0px))",background:"rgba(255,255,255,.98)",borderTop:`1px solid ${C.g1}`,zIndex:20}}><button onClick={()=>go("orderDone",{product:p,total})} style={{width:"100%",padding:"15px 0",borderRadius:R.m,border:"none",background:`linear-gradient(135deg,${C.red},${C.rDk})`,color:C.wh,fontSize:16,fontWeight:800,cursor:"pointer",fontFamily:F,boxShadow:`0 4px 18px ${C.red}44`}}>{fm(total)}원 결제하기</button></div>
  </div>);
}

/* ═══ ORDER DONE ═══ */
function OrderDone({product:p,total,go}){return(<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:40,textAlign:"center",background:C.bg,animation:"fu .5s ease"}}><div style={{fontSize:64,marginBottom:16}}>🎉</div><h2 style={{fontSize:22,fontWeight:900,fontFamily:F,marginBottom:6}}>결제 완료!</h2><p style={{fontSize:14,color:C.g5,lineHeight:1.6,marginBottom:24}}>공구 마감 후 배송이 시작됩니다</p><div style={{padding:16,background:C.wh,borderRadius:R.l,border:`1px solid ${C.g1}`,width:"100%",maxWidth:300,marginBottom:24}}><div style={{display:"flex",alignItems:"center",gap:12}}><Thumb p={p} size={48}/><div style={{textAlign:"left"}}><p style={{margin:0,fontSize:14,fontWeight:700}}>{p.name}</p><p style={{margin:"2px 0 0",fontSize:16,fontWeight:800,color:C.red}}>{fm(total)}원</p></div></div></div><div style={{display:"flex",gap:10,width:"100%",maxWidth:300}}><button onClick={()=>go("orders")} style={{flex:1,padding:"13px 0",borderRadius:R.m,border:`1px solid ${C.g2}`,background:C.wh,fontSize:14,fontWeight:700,fontFamily:F,cursor:"pointer"}}>주문내역</button><button onClick={()=>go("home")} style={{flex:1,padding:"13px 0",borderRadius:R.m,border:"none",background:C.dk,color:C.wh,fontSize:14,fontWeight:700,fontFamily:F,cursor:"pointer"}}>홈으로</button></div></div>)}

/* ═══ SHORTS ═══ */
function ShortsFeed({detail}){const[idx,setIdx]=useState(0);const[likes,setLikes]=useState({});const[muted,setMuted]=useState(true);const vRefs=useRef([]);const cRef=useRef(null);const shorts=P.map((p,i)=>({...p,caption:CAPTS[i]}));useEffect(()=>{const c=cRef.current;if(!c)return;const fn=()=>{const n=Math.round(c.scrollTop/c.clientHeight);if(n!==idx)setIdx(n)};c.addEventListener("scroll",fn,{passive:true});return()=>c.removeEventListener("scroll",fn)},[idx]);useEffect(()=>{vRefs.current.forEach((v,i)=>{if(!v)return;v.muted=muted;if(i===idx){v.currentTime=0;v.play().catch(()=>{})}else v.pause()})},[idx,muted]);
  return(<div ref={cRef} style={{height:"100vh",overflowY:"scroll",scrollSnapType:"y mandatory",background:"#000",scrollbarWidth:"none"}}>{shorts.map((s,i)=>(<div key={s.id} style={{height:"100vh",width:"100%",position:"relative",scrollSnapAlign:"start"}}><video ref={el=>vRefs.current[i]=el} src={s.video} muted={muted} autoPlay={i===0} loop playsInline preload={Math.abs(i-idx)<=1?"auto":"metadata"} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/><div style={{position:"absolute",bottom:0,left:0,right:0,height:"55%",background:"linear-gradient(transparent,rgba(0,0,0,.75))",pointerEvents:"none"}}/><div style={{position:"absolute",top:0,left:0,right:0,padding:"14px 20px",display:"flex",justifyContent:"space-between",alignItems:"center",zIndex:5}}><span style={{color:C.wh,fontSize:18,fontWeight:900}}>GUGU<span style={{color:C.red}}>.</span></span><Tap onClick={()=>setMuted(!muted)} style={{width:34,height:34,borderRadius:"50%",background:"rgba(255,255,255,.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16}}>{muted?"🔇":"🔊"}</Tap></div><div style={{position:"absolute",right:12,bottom:200,display:"flex",flexDirection:"column",gap:20,alignItems:"center",zIndex:5}}><Tap onClick={()=>setLikes(l=>({...l,[s.id]:!l[s.id]}))} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:2}}><div style={{width:44,height:44,borderRadius:"50%",background:"rgba(255,255,255,.12)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22}}>{likes[s.id]?"❤️":"🤍"}</div><span style={{fontSize:11,color:C.wh,fontFamily:MO}}>{fm(s.sold)}</span></Tap></div><div style={{position:"absolute",bottom:72,left:0,right:64,padding:"0 16px",zIndex:5}}><p style={{margin:"0 0 12px",fontSize:14,color:C.wh,lineHeight:1.5}}>{s.caption}</p><Tap onClick={()=>detail(s)} style={{background:"rgba(255,255,255,.12)",borderRadius:R.m,padding:"10px 12px",display:"flex",alignItems:"center",gap:10}}><Thumb p={s} size={48}/><div style={{flex:1,minWidth:0}}><p style={{margin:0,fontSize:13,fontWeight:700,color:C.wh,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{s.name}</p><span style={{fontSize:15,fontWeight:900,color:C.wh}}>{fm(s.price)}원</span></div><div style={{background:C.red,color:C.wh,fontSize:12,fontWeight:700,padding:"8px 14px",borderRadius:R.f}}>참여</div></Tap></div></div>))}</div>)}

/* ═══ ORDERS ═══ */
function OrdersPage({go,detail}){const[f,setF]=useState("전체");const sts=["전체","공구진행중","배송중","배송완료"];const list=f==="전체"?OD:OD.filter(o=>o.status===f);
  return(<div style={{paddingBottom:70}}><div style={{position:"sticky",top:0,zIndex:20,background:"rgba(250,250,250,.97)",padding:"0 20px",height:52,display:"flex",alignItems:"center",borderBottom:`1px solid ${C.g1}`}}><span style={{fontSize:17,fontWeight:800,fontFamily:F}}>주문내역</span></div><div style={{padding:"12px 20px 0",display:"flex",gap:6,overflowX:"auto",scrollbarWidth:"none"}}>{sts.map(s=>(<button key={s} onClick={()=>setF(s)} style={{padding:"6px 14px",borderRadius:R.f,border:"none",background:f===s?C.dk:C.wh,color:f===s?C.wh:C.g5,fontSize:12,fontWeight:f===s?700:500,fontFamily:F,cursor:"pointer",whiteSpace:"nowrap"}}>{s}</button>))}</div>
    <div style={{padding:"14px 20px"}}>{list.map((o,i)=>{const sm=SM[o.status];return(<Tap key={o.id} onClick={()=>go("orderDetail",{order:o})} style={{background:C.wh,borderRadius:R.l,padding:16,marginBottom:10,border:`1px solid ${C.g1}`,animation:`fu .3s ease ${i*.06}s both`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><span style={{fontSize:12,color:C.g4,fontFamily:MO}}>{o.id}</span><Bdg bg={sm.bg} color={sm.c}>{o.status}</Bdg></div><div style={{display:"flex",gap:12}}><Thumb p={o.product}/><div style={{flex:1,minWidth:0}}><p style={{margin:0,fontSize:14,fontWeight:700,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{o.product.name}</p><p style={{margin:"3px 0",fontSize:12,color:C.g4}}>수량 {o.qty}개 · {o.date}</p><p style={{margin:0,fontSize:15,fontWeight:800}}>{fm(o.total)}원</p></div></div>
      {o.status==="공구진행중"&&o.curP!=null&&<div style={{marginTop:12,padding:"10px 12px",background:"#FFF4EC",borderRadius:R.s}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:12,fontWeight:600,color:C.or}}>🔥 공구 진행중</span><Timer end={Date.now()+(o.hrsLeft||0)*36e5} size="sm"/></div><Bar cur={o.curP} goal={o.goalP} h={4}/></div>}
      {o.status==="배송중"&&<div style={{marginTop:12,padding:"10px 12px",background:C.gnB,borderRadius:R.s,display:"flex",alignItems:"center",gap:8}}><span>🚚</span><div style={{flex:1}}><p style={{margin:0,fontSize:12,fontWeight:600,color:C.gn}}>배송중</p><p style={{margin:"2px 0 0",fontSize:11,color:C.g5,fontFamily:MO}}>{o.track}</p></div></div>}
      {o.status==="배송완료"&&<div style={{marginTop:12,display:"flex",gap:6}}><button onClick={e=>{e.stopPropagation();detail(o.product)}} style={{flex:1,padding:"9px 0",borderRadius:R.s,border:`1px solid ${C.g2}`,background:C.wh,fontSize:12,fontWeight:600,cursor:"pointer"}}>재구매</button><button onClick={e=>{e.stopPropagation();go("writeReview",{product:o.product})}} style={{flex:1,padding:"9px 0",borderRadius:R.s,border:"none",background:C.dk,color:C.wh,fontSize:12,fontWeight:600,cursor:"pointer"}}>후기 작성</button></div>}
    </Tap>)})}</div></div>)}

/* ═══ ORDER DETAIL ═══ */
function OrderDetailPg({order:o,goBack}){const sm=SM[o.status];const steps=["결제완료","공구마감","배송준비","배송중","배송완료"];const si=o.status==="공구진행중"?0:o.status==="배송중"?3:4;
  return(<div style={{paddingBottom:20,background:C.g0}}><Hdr title="주문 상세" left onLeft={goBack}/><div style={{margin:"6px 0",padding:16,background:C.wh}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontSize:12,color:C.g4,fontFamily:MO}}>{o.id}</span><Bdg bg={sm.bg} color={sm.c}>{o.status}</Bdg></div><div style={{display:"flex",gap:12}}><Thumb p={o.product}/><div><p style={{margin:0,fontSize:14,fontWeight:700}}>{o.product.name}</p><p style={{margin:"3px 0",fontSize:12,color:C.g4}}>수량 {o.qty}개</p><p style={{margin:0,fontSize:16,fontWeight:800}}>{fm(o.total)}원</p></div></div></div>
    <div style={{margin:"0 0 6px",padding:16,background:C.wh}}><h3 style={{margin:"0 0 14px",fontSize:15,fontWeight:800}}>진행 상태</h3>{steps.map((s,i)=>{const done=i<=si,act=i===si;return(<div key={i} style={{display:"flex",gap:12}}><div style={{display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{width:20,height:20,borderRadius:"50%",background:done?act?C.red:C.gn:C.g1,display:"flex",alignItems:"center",justifyContent:"center",color:C.wh,fontSize:10,fontWeight:800}}>{done&&(act?"●":"✓")}</div>{i<4&&<div style={{width:2,height:24,background:done?C.gn:C.g1,margin:"2px 0"}}/>}</div><div style={{paddingBottom:i<4?12:0}}><span style={{fontSize:13,fontWeight:act?700:400,color:done?C.dk:C.g3}}>{s}</span></div></div>)})}</div>
    {o.status==="공구진행중"&&o.curP!=null&&<div style={{margin:"0 0 6px",padding:16,background:C.wh}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><span style={{fontSize:14,fontWeight:700,color:C.or}}>🔥 공구 현황</span><Timer end={Date.now()+(o.hrsLeft||0)*36e5} size="sm"/></div><Bar cur={o.curP} goal={o.goalP}/></div>}
    <div style={{margin:"0 0 6px",padding:16,background:C.wh}}><h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:800}}>결제 정보</h3>{[{l:"결제일",v:o.date},{l:"결제수단",v:o.pay},{l:"상품 금액",v:fm(o.total)+"원"},{l:"배송비",v:"무료"},{l:"총 결제",v:fm(o.total)+"원",b:true}].map(r=>(<div key={r.l} style={{display:"flex",justifyContent:"space-between",marginBottom:6,fontSize:13}}><span style={{color:C.g5}}>{r.l}</span><span style={{fontWeight:r.b?800:500,color:r.b?C.red:C.dk}}>{r.v}</span></div>))}</div>
    <div style={{padding:16,background:C.wh}}><h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:800}}>배송지</h3><p style={{margin:0,fontSize:14,fontWeight:600}}>홍길동 · 010-1234-5678</p><p style={{margin:"4px 0 0",fontSize:13,color:C.g5}}>{o.addr}</p>{o.track&&<p style={{margin:"8px 0 0",fontSize:12,color:C.gn,fontFamily:MO}}>📦 {o.track}</p>}</div>
  </div>)}

/* ═══ WRITE REVIEW ═══ */
function WriteReview({product:p,goBack,go}){const[stars,setStars]=useState(0);const[text,setText]=useState("");const[done,setDone]=useState(false);
  if(done)return(<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:40,textAlign:"center",animation:"fu .4s ease"}}><div style={{fontSize:64,marginBottom:16}}>⭐</div><h2 style={{fontSize:20,fontWeight:800,marginBottom:6}}>후기 작성 완료!</h2><p style={{fontSize:14,color:C.g5,marginBottom:8}}>500P가 적립되었어요</p><button onClick={()=>go("orders")} style={{padding:"12px 28px",borderRadius:R.f,background:C.dk,color:C.wh,border:"none",fontSize:14,fontWeight:700,cursor:"pointer"}}>확인</button></div>);
  return(<div style={{paddingBottom:90,background:C.g0}}>
    <Hdr title="후기 작성" left onLeft={goBack}/>
    <div style={{margin:"6px 0",padding:16,background:C.wh}}><div style={{display:"flex",gap:12,marginBottom:16}}><Thumb p={p}/><div><p style={{margin:0,fontSize:14,fontWeight:700}}>{p.name}</p><p style={{margin:"3px 0 0",fontSize:12,color:C.g4}}>{p.inf.name}님의 공구</p></div></div>
      <div style={{textAlign:"center",marginBottom:20}}><p style={{margin:"0 0 10px",fontSize:14,fontWeight:700}}>상품은 어떠셨나요?</p><div style={{display:"flex",justifyContent:"center",gap:6}}>{[1,2,3,4,5].map(i=>(<span key={i} onClick={()=>setStars(i)} style={{fontSize:36,cursor:"pointer",transition:"transform .15s",transform:i<=stars?"scale(1.1)":"scale(1)"}}>{i<=stars?"⭐":"☆"}</span>))}</div>{stars>0&&<p style={{margin:"8px 0 0",fontSize:13,color:C.red,fontWeight:600}}>{["","별로예요","그저 그래요","괜찮아요","좋아요","최고예요!"][stars]}</p>}</div>
      <textarea value={text} onChange={e=>setText(e.target.value)} placeholder="솔직한 후기를 남겨주세요 (최소 20자)" rows={5} style={{width:"100%",padding:14,borderRadius:R.m,border:`1px solid ${text.length>=20?C.gn:C.g1}`,fontSize:14,fontFamily:F,outline:"none",resize:"none",boxSizing:"border-box",transition:"border .2s"}}/>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:6}}><span style={{fontSize:12,color:text.length>=20?C.gn:C.g4}}>{text.length}자 / 최소 20자</span><span style={{fontSize:12,color:C.g4}}>작성 시 500P 적립</span></div>
    </div>
    <div style={{position:"fixed",bottom:0,left:0,right:0,maxWidth:480,margin:"0 auto",padding:"8px 20px",paddingBottom:"calc(8px + env(safe-area-inset-bottom,0px))",background:"rgba(255,255,255,.98)",borderTop:`1px solid ${C.g1}`,zIndex:20}}><button onClick={()=>{if(stars>0&&text.length>=20)setDone(true)}} disabled={stars===0||text.length<20} style={{width:"100%",padding:"14px 0",borderRadius:R.m,border:"none",background:stars>0&&text.length>=20?`linear-gradient(135deg,${C.red},${C.rDk})`:C.g1,color:stars>0&&text.length>=20?C.wh:C.g3,fontSize:15,fontWeight:800,cursor:stars>0&&text.length>=20?"pointer":"default",fontFamily:F,transition:"all .2s"}}>후기 등록하기</button></div>
  </div>)}

/* ═══ NOTIFICATIONS ═══ */
function NotifsPage({goBack,detail}){const[nots,setNots]=useState(NOTIFS);return(<div style={{paddingBottom:20}}><Hdr title="알림" left onLeft={goBack}/><div style={{padding:"8px 20px"}}>{nots.map((n,i)=>(<Tap key={n.id} onClick={()=>{setNots(ns=>ns.map(x=>x.id===n.id?{...x,read:true}:x));if(n.pid){const prod=P.find(p=>p.id===n.pid);if(prod)detail(prod)}}} style={{display:"flex",gap:12,padding:"14px 0",borderBottom:`1px solid ${C.g1}`,opacity:n.read?.65:1,animation:`fu .3s ease ${i*.04}s both`}}><div style={{width:42,height:42,borderRadius:R.m,background:n.read?C.g0:C.rBg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,flexShrink:0}}>{n.icon}</div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between"}}><p style={{margin:0,fontSize:14,fontWeight:n.read?500:700}}>{n.title}</p>{!n.read&&<span style={{width:6,height:6,borderRadius:"50%",background:C.red,flexShrink:0,marginTop:6}}/>}</div><p style={{margin:"3px 0 0",fontSize:13,color:C.g5}}>{n.body}</p><p style={{margin:"4px 0 0",fontSize:11,color:C.g3}}>{n.time}</p></div></Tap>))}</div></div>)}

/* ═══ INFLUENCER ═══ */
function InfluencerPage({inf,goBack,detail}){const deals=P.filter(p=>p.inf.id===inf.id);return(<div style={{paddingBottom:70}}><Hdr title="셀러 프로필" left onLeft={goBack}/><div style={{padding:20,textAlign:"center",background:C.wh}}><div style={{width:80,height:80,borderRadius:"50%",background:`linear-gradient(135deg,${C.red},${C.rDk})`,padding:3,margin:"0 auto"}}><div style={{width:"100%",height:"100%",borderRadius:"50%",background:`linear-gradient(135deg,${inf.color},${inf.color}cc)`,display:"flex",alignItems:"center",justifyContent:"center",color:C.wh,fontSize:24,fontWeight:900,border:`3px solid ${C.wh}`}}>{inf.short}</div></div><h2 style={{margin:"12px 0 4px",fontSize:20,fontWeight:800}}>{inf.name}</h2><p style={{margin:"0 0 16px",fontSize:13,color:C.g4,fontFamily:MO}}>팔로워 {inf.fol} · 성공률 {inf.rate}%</p><button style={{padding:"10px 32px",borderRadius:R.f,background:C.dk,color:C.wh,border:"none",fontSize:14,fontWeight:700,cursor:"pointer"}}>팔로우</button></div><div style={{padding:"16px 20px"}}><h3 style={{margin:"0 0 12px",fontSize:16,fontWeight:800}}>진행중 공구 <span style={{color:C.red,fontFamily:MO}}>{deals.length}</span></h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{deals.map((d,i)=>(<Card key={d.id} item={d} i={i} onClick={()=>detail(d)}/>))}</div></div></div>)}

/* ═══ COUPONS ═══ */
function CouponsPage({goBack}){const avail=COUPONS.filter(c=>!c.used);const used=COUPONS.filter(c=>c.used);return(<div style={{paddingBottom:20}}><Hdr title="쿠폰함" left onLeft={goBack}/><div style={{padding:"12px 20px"}}><p style={{fontSize:13,color:C.g5,marginBottom:14}}>사용 가능 <b style={{color:C.dk}}>{avail.length}장</b></p>{avail.map(c=>(<div key={c.id} style={{background:C.wh,borderRadius:R.l,padding:16,marginBottom:8,border:`1px solid ${C.g1}`,borderLeft:`4px solid ${C.red}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><p style={{margin:0,fontSize:20,fontWeight:900,color:C.red}}>{fm(c.amount)}원</p><p style={{margin:"4px 0 2px",fontSize:14,fontWeight:700}}>{c.name}</p><p style={{margin:0,fontSize:12,color:C.g4}}>~{c.exp} · {fm(c.min)}원 이상</p></div><button style={{padding:"8px 16px",borderRadius:R.f,background:C.red,color:C.wh,border:"none",fontSize:12,fontWeight:700,cursor:"pointer",flexShrink:0}}>사용</button></div></div>))}{used.length>0&&<><p style={{fontSize:13,color:C.g4,margin:"16px 0 10px"}}>사용완료/만료</p>{used.map(c=>(<div key={c.id} style={{background:C.g0,borderRadius:R.l,padding:16,marginBottom:8,opacity:.5}}><p style={{margin:0,fontSize:18,fontWeight:800,color:C.g4}}>{fm(c.amount)}원</p><p style={{margin:"3px 0 0",fontSize:13,color:C.g4}}>{c.name} · ~{c.exp}</p></div>))}</>}</div></div>)}

/* ═══ POINTS ═══ */
function PointsPage({goBack}){const total=PLOG.reduce((s,p)=>s+p.amount,0);return(<div style={{paddingBottom:20}}><Hdr title="포인트" left onLeft={goBack}/><div style={{padding:20,textAlign:"center",background:C.wh,borderBottom:`1px solid ${C.g1}`}}><p style={{margin:0,fontSize:12,color:C.g4}}>보유 포인트</p><p style={{margin:"6px 0 0",fontSize:32,fontWeight:900,fontFamily:MO}}>{fm(total)}P</p></div><div style={{padding:"14px 20px"}}>{PLOG.map(p=>(<div key={p.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"12px 0",borderBottom:`1px solid ${C.g1}`}}><div><p style={{margin:0,fontSize:14,fontWeight:600}}>{p.desc}</p><p style={{margin:"2px 0 0",fontSize:12,color:C.g4}}>{p.date}</p></div><span style={{fontSize:15,fontWeight:800,color:p.type==="+"?C.gn:C.red,fontFamily:MO}}>{p.type}{fm(Math.abs(p.amount))}P</span></div>))}</div></div>)}

/* ═══ WISHLIST ═══ */
function WishPage({goBack,detail}){return(<div style={{paddingBottom:70}}><Hdr title="찜한 공구" left onLeft={goBack}/><div style={{padding:"10px 20px"}}><p style={{fontSize:13,color:C.g4,marginBottom:12}}>총 <b style={{color:C.dk}}>3</b>개</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{P.slice(0,3).map((p,i)=>(<Card key={p.id} item={p} i={i} onClick={()=>detail(p)}/>))}</div></div></div>)}

/* ═══ MY REVIEWS ═══ */
function MyReviewsPage({goBack}){return(<div style={{paddingBottom:20}}><Hdr title="내가 쓴 후기" left onLeft={goBack}/><div style={{padding:"14px 20px"}}>{MY_RV.map(r=>(<div key={r.id} style={{background:C.wh,borderRadius:R.l,padding:16,marginBottom:10,border:`1px solid ${C.g1}`}}><div style={{display:"flex",gap:12,marginBottom:10}}><Thumb p={r.product} size={52}/><div><p style={{margin:0,fontSize:14,fontWeight:700}}>{r.product.name}</p><div style={{display:"flex",alignItems:"center",gap:4,marginTop:3}}><Stars r={r.rating} size={12}/><span style={{fontSize:12,color:C.g4}}>{r.date}</span></div></div></div><p style={{margin:0,fontSize:13,color:C.g7,lineHeight:1.6}}>{r.text}</p></div>))}</div></div>)}

/* ═══ EVENTS ═══ */
function EventsPage({goBack}){return(<div style={{paddingBottom:20}}><Hdr title="이벤트" left onLeft={goBack}/><div style={{padding:"14px 20px"}}>{EVENTS.map(e=>(<Tap key={e.id} style={{background:C.wh,borderRadius:R.l,padding:16,marginBottom:10,border:`1px solid ${C.g1}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}><span style={{fontSize:32}}>{e.emoji}</span><Bdg bg={e.tag==="마감임박"?C.rBg:e.tag==="진행중"?C.gnB:C.g0} color={e.tag==="마감임박"?C.red:e.tag==="진행중"?C.gn:C.g5}>{e.tag}</Bdg></div><h3 style={{margin:"0 0 4px",fontSize:16,fontWeight:800}}>{e.title}</h3><p style={{margin:"0 0 6px",fontSize:13,color:C.g5,lineHeight:1.5}}>{e.desc}</p><p style={{margin:0,fontSize:12,color:C.g4}}>{e.period}</p></Tap>))}</div></div>)}

/* ═══ PROFILE EDIT ═══ */
function ProfilePage({goBack}){const[name,setName]=useState("홍길동");const[phone]=useState("010-1234-5678");const[saved,setSaved]=useState(false);
  return(<div style={{paddingBottom:90,background:C.g0}}><Hdr title="회원정보 수정" left onLeft={goBack}/><div style={{margin:"6px 0",padding:16,background:C.wh}}>
    {[{l:"이름",v:name,onChange:setName},{l:"연락처",v:phone,disabled:true},{l:"이메일",v:"gugu@email.com",disabled:true}].map(f=>(<div key={f.l} style={{marginBottom:14}}><p style={{margin:"0 0 6px",fontSize:13,fontWeight:600,color:C.g5}}>{f.l}</p><input value={f.v} onChange={f.onChange?e=>f.onChange(e.target.value):undefined} disabled={f.disabled} style={{width:"100%",padding:"11px 14px",borderRadius:R.s,border:`1px solid ${C.g1}`,fontSize:14,fontFamily:F,outline:"none",boxSizing:"border-box",background:f.disabled?C.g0:C.wh,color:f.disabled?C.g4:C.dk}}/></div>))}
    <div style={{marginBottom:14}}><p style={{margin:"0 0 6px",fontSize:13,fontWeight:600,color:C.g5}}>기본 배송지</p><input defaultValue="서울특별시 강남구 테헤란로 123, 4층" style={{width:"100%",padding:"11px 14px",borderRadius:R.s,border:`1px solid ${C.g1}`,fontSize:14,fontFamily:F,outline:"none",boxSizing:"border-box"}}/></div>
  </div>
  <div style={{position:"fixed",bottom:0,left:0,right:0,maxWidth:480,margin:"0 auto",padding:"8px 20px",paddingBottom:"calc(8px + env(safe-area-inset-bottom,0px))",background:"rgba(255,255,255,.98)",borderTop:`1px solid ${C.g1}`,zIndex:20}}><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2000)}} style={{width:"100%",padding:"14px 0",borderRadius:R.m,border:"none",background:C.dk,color:C.wh,fontSize:15,fontWeight:800,cursor:"pointer"}}>{saved?"✓ 저장 완료":"저장하기"}</button></div>
  </div>)}

/* ═══ FAQ ═══ */
function FaqPage({goBack}){const[open,setOpen]=useState(null);return(<div style={{paddingBottom:20}}><Hdr title="고객센터" left onLeft={goBack}/><div style={{padding:"8px 20px"}}>
    <div style={{padding:"16px",background:C.rBg,borderRadius:R.l,marginBottom:16,textAlign:"center"}}><p style={{margin:0,fontSize:14,fontWeight:700,color:C.red}}>📞 상담 문의</p><p style={{margin:"4px 0 0",fontSize:13,color:C.g5}}>평일 10:00~18:00 (점심 12~13시 제외)</p><p style={{margin:"2px 0 0",fontSize:15,fontWeight:800,fontFamily:MO}}>02-1234-5678</p></div>
    <h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:800}}>자주 묻는 질문</h3>
    {FAQ.map((f,i)=>(<div key={i} style={{background:C.wh,borderRadius:R.m,marginBottom:6,border:`1px solid ${C.g1}`,overflow:"hidden"}}>
      <Tap onClick={()=>setOpen(open===i?null:i)} style={{padding:"14px 16px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:14,fontWeight:600}}>{f.q}</span><span style={{fontSize:14,color:C.g3,transition:"transform .2s",transform:open===i?"rotate(180deg)":"rotate(0)"}}>{open===i?"▲":"▼"}</span></Tap>
      {open===i&&<div style={{padding:"0 16px 14px",fontSize:13,color:C.g5,lineHeight:1.6,animation:"fu .2s ease"}}>{f.a}</div>}
    </div>))}
  </div></div>)}

/* ═══ TERMS ═══ */
function TermsPage({goBack}){return(<div style={{paddingBottom:20}}><Hdr title="이용약관" left onLeft={goBack}/><div style={{padding:"14px 20px"}}>
    {["서비스 이용약관","개인정보 처리방침","전자금융거래 이용약관","위치기반 서비스 이용약관"].map((t,i)=>(<Tap key={i} style={{padding:"14px 0",borderBottom:`1px solid ${C.g1}`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:14}}>{t}</span><span style={{color:C.g3}}>›</span></Tap>))}
    <div style={{marginTop:24,padding:16,background:C.g0,borderRadius:R.m}}><p style={{margin:0,fontSize:12,color:C.g4,lineHeight:1.6}}>주식회사 구구 | 대표: 홍길동<br/>사업자등록번호: 123-45-67890<br/>통신판매업신고: 제2026-서울강남-12345호<br/>주소: 서울특별시 강남구 테헤란로 123<br/>고객센터: 02-1234-5678<br/>이메일: help@gugu.kr</p></div>
  </div></div>)}

/* ═══ MY PAGE ═══ */
function MyPage({go}){return(<div style={{paddingBottom:70}}><div style={{position:"sticky",top:0,zIndex:20,background:"rgba(250,250,250,.97)",padding:"0 20px",height:52,display:"flex",alignItems:"center",borderBottom:`1px solid ${C.g1}`}}><span style={{fontSize:17,fontWeight:800,fontFamily:F}}>MY</span></div>
    <div style={{padding:20,display:"flex",alignItems:"center",gap:14}}><div style={{width:56,height:56,borderRadius:"50%",background:`linear-gradient(135deg,${C.red},#FF7B73)`,display:"flex",alignItems:"center",justifyContent:"center",color:C.wh,fontSize:22,fontWeight:800}}>G</div><div style={{flex:1}}><p style={{margin:0,fontSize:17,fontWeight:800}}>구구 회원</p><p style={{margin:"2px 0 0",fontSize:13,color:C.g4}}>혜택을 받아보세요</p></div><Tap onClick={()=>{}} style={{padding:"8px 16px",borderRadius:R.f,background:C.dk,color:C.wh,fontSize:13,fontWeight:700}}><span>로그인</span></Tap></div>
    <div style={{padding:"0 20px 16px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",background:C.wh,borderRadius:R.l,border:`1px solid ${C.g1}`}}>
      {[{l:"쿠폰",v:`${COUPONS.filter(c=>!c.used).length}장`,i:"🎫",act:()=>go("coupons")},{l:"포인트",v:`${fm(PLOG.reduce((s,p)=>s+p.amount,0))}P`,i:"💰",act:()=>go("points")},{l:"찜",v:"3개",i:"❤️",act:()=>go("wish")}].map((s,idx)=>(<Tap key={s.l} onClick={s.act} style={{textAlign:"center",padding:"16px 8px",borderRight:idx<2?`1px solid ${C.g1}`:"none"}}><span style={{fontSize:22}}>{s.i}</span><p style={{margin:"4px 0 1px",fontSize:16,fontWeight:800}}>{s.v}</p><p style={{margin:0,fontSize:11,color:C.g4}}>{s.l}</p></Tap>))}
    </div></div>
    {[
      {t:"쇼핑 정보",items:[{i:"📦",l:"주문/배송 조회",a:()=>go("orders")},{i:"↩️",l:"교환/반품 내역",a:()=>go("orders")},{i:"⭐",l:"내가 쓴 후기",a:()=>go("myReviews")}]},
      {t:"혜택",items:[{i:"🎫",l:"쿠폰함",a:()=>go("coupons")},{i:"💰",l:"포인트 내역",a:()=>go("points")},{i:"🎁",l:"이벤트",a:()=>go("events")}]},
      {t:"설정",items:[{i:"👤",l:"회원정보 수정",a:()=>go("profile")},{i:"🔔",l:"알림 설정",a:()=>go("notif")},{i:"❓",l:"고객센터",a:()=>go("faq")},{i:"📄",l:"이용약관",a:()=>go("terms")}]},
    ].map((sec,si)=>(<div key={si} style={{padding:"0 20px",marginBottom:6}}><p style={{fontSize:12,fontWeight:700,color:C.g4,margin:"12px 0 6px"}}>{sec.t}</p><div style={{background:C.wh,borderRadius:R.l,border:`1px solid ${C.g1}`,overflow:"hidden"}}>{sec.items.map((item,i)=>(<div key={i} style={{borderBottom:i<sec.items.length-1?`1px solid ${C.g1}`:"none"}}><MenuRow icon={item.i} label={item.l} onClick={item.a}/></div>))}</div></div>))}
    <div style={{padding:20,textAlign:"center"}}><span style={{fontSize:12,color:C.g3}}>GUGU v1.0.0</span></div>
  </div>)}

/* ═══ APP ═══ */
export default function App(){
  const[stack,setStack]=useState([{page:"home",data:{}}]);const cur=stack[stack.length-1];const ref=useRef(null);
  const go=useCallback((p,d={})=>{const tabs=["home","shorts","orders","my"];if(tabs.includes(p))setStack([{page:p,data:d}]);else setStack(s=>[...s,{page:p,data:d}]);if(ref.current)ref.current.scrollTop=0},[]);
  const back=useCallback(()=>{setStack(s=>s.length>1?s.slice(0,-1):[{page:"home",data:{}}]);if(ref.current)ref.current.scrollTop=0},[]);
  const detail=useCallback(p=>go("detail",{product:p}),[go]);
  const at=["home","shorts","orders","my"].includes(cur.page)?cur.page:stack[0]?.page||"home";
  const hideNav=!["home","shorts","orders","my"].includes(cur.page);
  const isShorts=cur.page==="shorts";

  return(<div style={{display:"flex",justifyContent:"center",minHeight:"100vh",background:"#E2E2E2"}}>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet"/>
    <style>{`@keyframes bp{0%,100%{opacity:1}50%{opacity:.4}}@keyframes fu{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}@keyframes su{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}@keyframes sd{from{opacity:0;transform:translateY(-14px)}to{opacity:1;transform:translateY(0)}}@keyframes fo{to{opacity:0;transform:translateY(-14px);pointer-events:none}}*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;margin:0}::-webkit-scrollbar{display:none}html{-webkit-text-size-adjust:100%}input,textarea{font-size:16px;font-family:${F}}`}</style>
    <div ref={ref} style={{width:"100%",maxWidth:480,minHeight:"100vh",background:isShorts?"#000":C.bg,position:"relative",overflowY:isShorts?"hidden":"auto",overflowX:"hidden"}}>
      {cur.page==="home"&&<Home go={go} detail={detail}/>}
      {cur.page==="shorts"&&<ShortsFeed detail={detail}/>}
      {cur.page==="search"&&<SearchPage go={go} detail={detail}/>}
      {cur.page==="detail"&&<Detail product={cur.data.product} goBack={back} go={go}/>}
      {cur.page==="checkout"&&<Checkout product={cur.data.product} qty={cur.data.qty} goBack={back} go={go}/>}
      {cur.page==="orderDone"&&<OrderDone product={cur.data.product} total={cur.data.total} go={go}/>}
      {cur.page==="influencer"&&<InfluencerPage inf={cur.data.inf} goBack={back} detail={detail}/>}
      {cur.page==="orders"&&<OrdersPage go={go} detail={detail}/>}
      {cur.page==="orderDetail"&&<OrderDetailPg order={cur.data.order} goBack={back}/>}
      {cur.page==="writeReview"&&<WriteReview product={cur.data.product} goBack={back} go={go}/>}
      {cur.page==="notif"&&<NotifsPage goBack={back} detail={detail}/>}
      {cur.page==="coupons"&&<CouponsPage goBack={back}/>}
      {cur.page==="points"&&<PointsPage goBack={back}/>}
      {cur.page==="wish"&&<WishPage goBack={back} detail={detail}/>}
      {cur.page==="myReviews"&&<MyReviewsPage goBack={back}/>}
      {cur.page==="events"&&<EventsPage goBack={back}/>}
      {cur.page==="profile"&&<ProfilePage goBack={back}/>}
      {cur.page==="faq"&&<FaqPage goBack={back}/>}
      {cur.page==="terms"&&<TermsPage goBack={back}/>}
      {cur.page==="my"&&<MyPage go={go}/>}

      {!hideNav&&<nav style={{position:"fixed",bottom:0,left:0,right:0,maxWidth:480,margin:"0 auto",height:56,paddingBottom:"env(safe-area-inset-bottom,0px)",background:isShorts?"rgba(0,0,0,.9)":C.wh,borderTop:`1px solid ${isShorts?"rgba(255,255,255,.1)":C.g1}`,display:"flex",justifyContent:"space-around",alignItems:"center",zIndex:30}}>
        {[{id:"home",i:"🏠",l:"홈"},{id:"shorts",i:"🎬",l:"숏폼"},{id:"orders",i:"📦",l:"주문"},{id:"my",i:"👤",l:"MY"}].map(t=>{const on=at===t.id;return(<Tap key={t.id} onClick={()=>go(t.id)} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:1,padding:"5px 14px"}}><span style={{fontSize:19,opacity:on?1:.3}}>{t.i}</span><span style={{fontSize:10,fontWeight:on?700:500,color:on?C.red:isShorts?"rgba(255,255,255,.4)":C.g4,fontFamily:F}}>{t.l}</span></Tap>)})}
      </nav>}
    </div>
  </div>);
}
